version: '3.7'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - '27017-27019:27017-27019'
    volumes:
      - './mongo-entrypoint:/docker-entrypoint-initdb.d'
      - 'mongodb_data:/data/db'
      - 'mongoconfig:/data/configdb'
    networks:
      - mongo_network
volumes:
  mongodb_data: null
  mongoconfig: null

networks:
  mongo_network:
    driver: bridge
