version: '3.2'

services:
   mysql_server:
      image: mysql:5.7.22
      container_name: mysql_server
      restart: always
      ports:
         - '3306:3306'
      environment:
         MYSQL_ROOT_PASSWORD: root
         MYSQL_USER: root
         MYSQL_PASSWORD: root
      volumes:
         - ./databases:/var/lib/mysql
         - ./logs:/var/log/mysql
      networks:
         - app-network
   phpmyadmin:
      depends_on:
       - mysql_server
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin
      restart: always
      ports:
       - '8080:80'
      environment:
        PMA_HOST: mysql_server
      networks:
         - app-network

#Docker Networks
networks:
   app-network:
      driver: bridge
