version: '3.1'

services:
  go:
    image: golang:1.12-alpine
    command: sh -c "go run ."
    environment:
      - PORT=5000
    ports:
      - '5000:5000'
    working_dir: /root/go
    volumes:
      - ./web:/root/go:cached # <--- This will map ./python to /root/python inside the container.
